# Generated by Django 5.0.1 on 2024-01-24 13:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='address',
        ),
        migrations.RemoveField(
            model_name='student',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='student',
            name='username',
        ),
    ]
