# Generated by Django 5.0.1 on 2024-01-31 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_student_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='role',
            field=models.CharField(default='student', max_length=100),
        ),
    ]
