# Generated by Django 5.0.1 on 2024-01-31 14:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_invite_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='token',
        ),
    ]
